include:
  - _base/jobs.yml
  - _base/vars.yml
  - _base/stages.yml
  - _base/rules.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        APPSEC_SKIP: "true"
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - when: always
